module.exports = {
  plugins: [require('@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss')],
  trailingComma: 'es5',
  tabWidth: 2,
  printWidth: 120,
  semi: false,
  singleQuote: true,
  jsxSingleQuote: true,
  bracketSameLine: false,
  bracketSpacing: true,
  importOrder: [
    '',
    '<BUILTIN_MODULES>',
    '',
    '^react$',
    '',
    'react-icons',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/components/(.*)$',
    '',
    '^[./]',
    '',
    '<TYPES>',
    '<TYPES>^[.]',
    '',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],
}
